---
title: "Learning data visualization"
output: html_notebook
---

```{r}
library(tidyverse)
```


#Relationship between engine size and fuel efficiency:

```{r}
data = mpg

ggplot(data) + geom_point(mapping = aes(x = displ, y = hwy))
```

```{r}
ggplot(data) + geom_point(mapping = aes(x = hwy, y = cyl))
```
```{r}
ggplot(data) + geom_point(mapping = aes(x = class, y = drv))
```

```{r}
ggplot(data) + geom_point(mapping = aes(x = displ, y = hwy, color = class))
```

```{r}
ggplot(data) + geom_point(mapping = aes(x = displ, y = hwy, size = class))
```
```{r}
ggplot(data) + geom_point(mapping = aes(x = displ, y = hwy, alpha = class))
```
```{r}
ggplot(data) + geom_point(mapping = aes(x = displ, y = hwy, shape = class))
```
```{r}
ggplot(data) + geom_point(mapping = aes(x = displ, y = hwy), color = "blue")
```

```{r}
ggplot(data) + geom_point(mapping = aes(x = displ, y = hwy, color = displ < 5))
```

#Facets

```{r}
ggplot(data) + geom_point(mapping = aes(x = displ, y = hwy)) + facet_wrap(~ class, nrow = 3)
```

```{r}
ggplot(data) + geom_point(mapping = aes(x = displ, y = hwy)) + facet_grid(drv ~ cyl)
```

```{r}
ggplot(data) + geom_point(mapping = aes(x = displ, y = hwy)) + facet_grid(. ~ cyl)
```

```{r}
ggplot(data) + geom_point(mapping = aes(x = displ, y = hwy)) + facet_grid(. ~ displ)
```

```{r}
ggplot(data = mpg) + geom_point(mapping = aes(x = drv, y = cyl))
```

# Geoms

```{r}
ggplot(data) + geom_smooth(mapping = aes(x = displ, y = hwy), method = loess)
```

```{r}
ggplot(data) + geom_smooth(mapping = aes(x = displ, y = hwy, linetype = drv))
```

```{r}
ggplot(data) + geom_smooth(mapping = aes(x = displ, y = hwy, linetype = drv, color = drv), method = loess) + geom_point(mapping = aes(x = displ, y = hwy, color = drv))
```

```{r}
ggplot(data) + geom_smooth(mapping = aes(x = displ, y = hwy, color = drv), show.legend = F, method = loess)
```

```{r}
ggplot(data) + geom_point(mapping = aes(x = displ, y = hwy)) + geom_smooth(mapping = aes( x = displ, y = hwy))
```

Bolji naÄin za izvesti ovo gore - nema duplikacije koda!

```{r}
ggplot(data, mapping = aes(x = displ, y = hwy)) + geom_point() + geom_smooth(method = loess)
```

```{r}
ggplot(data, mapping = aes(x = displ, y = hwy)) + geom_point(mapping = aes(color = class)) + geom_smooth()
```

```{r}
ggplot(data, mapping = aes(x = displ, y = hwy)) + geom_point(mapping = aes(color = class)) + geom_smooth(data = filter(data, class == "suv"), color = "red")
```

```{r}
ggplot(data, mapping = aes(x = displ, y = hwy, color = drv)) + geom_point() + geom_smooth(se = F)
```

```{r}
ggplot(data, mapping = aes(x = displ, y = hwy)) + geom_point() + geom_smooth(se = F, method = loess) 
```

```{r}
ggplot(data, mapping = aes(x = displ, y = hwy, group = drv)) + geom_point() + geom_smooth(se = F, method = loess)
```

```{r}
ggplot(data, mapping = aes(x = displ, y = hwy, color = drv)) + geom_point() + geom_smooth(se = F, method = loess)
```

```{r}
ggplot(data, mapping = aes(x = displ, y = hwy)) + geom_point(mapping = aes(color = drv)) + geom_smooth(se = F, method = loess)
```

```{r}
ggplot(data, mapping = aes(x = displ, y = hwy)) + geom_point(mapping = aes(color = drv)) + geom_smooth(mapping = aes(linetype = drv), se = F, method = loess)
```

# Statistical transformations

```{r}
ggplot(data = diamonds) + geom_bar(mapping = aes(x = cut, fill = cut))
```

```{r}
ggplot(data = diamonds) + stat_count(mapping = aes(x = cut))
```

```{r}
ggplot(data = diamonds) + geom_bar(mapping = aes(x = cut, y = ..prop.., group = 1))
```

```{r}
ggplot(data = diamonds) + stat_summary(mapping = aes(x = cut, y = depth),
                                       fun.ymin = min,
                                       fun.ymax = max,
                                       fun.y = median)
```

```{r}
ggplot(data = diamonds) + geom_bar(mapping = aes(x = cut, y = ..prop..))
```

```{r}
ggplot(data = diamonds) + geom_bar(mapping = aes(x = cut, fill = color, y = ..prop..))
```

```{r}
ggplot(data = diamonds) + geom_bar(mapping = aes(x = cut, fill = clarity))
```

```{r}
ggplot(data = diamonds) + geom_bar(mapping = aes(x = cut, fill = clarity, position = "identity", alpha = 1/5))
```

```{r}
ggplot(data = diamonds) + geom_bar(mapping = aes(x = cut, fill = clarity), position = "fill")
```

```{r}
ggplot(data = diamonds) + geom_bar(mapping = aes(x = cut, fill = clarity), position = "dodge")
```

# Jittering - adding random noise to make graphs more revealing at large scales


```{r}
ggplot(data = mpg) + geom_jitter(mapping = aes(x = displ, y = hwy))
```

```{r}
ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) + geom_jitter(mapping = aes(color = "red")) + geom_count(mapping = aes(alpha = 4/5))
```
# Box plots

```{r}
ggplot(data = mpg, mapping = aes(x = factor(cyl), y = hwy)) + geom_boxplot()
```

# Coordinate systems

```{r}
ggplot(data = mpg, mapping = aes(x = class, y = hwy)) + geom_boxplot()
```

```{r}
ggplot(data = mpg, mapping = aes(x = class, y = hwy)) + geom_boxplot() + coord_flip()
```

```{r}
bar <- ggplot(data = diamonds) + geom_bar(mapping = aes(x = cut, fill = cut), show.legend = F, width = 1) + theme(aspect.ratio = 1) + labs(x = NULL, y = NULL)
```

```{r}
bar
```

```{r}
bar + coord_flip()
```

```{r}
bar + coord_polar()
```

