---
title: "Data transformation"
output: html_notebook
---


```{r}
library(tidyverse)
library(nycflights13)
```

# Filtering with filter()

```{r}
filter(flights, month == 1, day == 1)
```

```{r}
jan1 <- filter(flights, month == 1, day == 1)
```

```{r}
(dec25 <- filter(flights, month == 12, day == 25))
```

```{r}
filter(flights, month == 11 | month == 12)
```

```{r}
(nov_dec <- filter(flights, month %in% c(11, 12)))
```


```{r}
filter(flights, !(arr_delay > 120 | dep_delay > 120))
```

```{r}
df <- tibble(x = c(1, NA, 3))
filter(df, x > 1)
filter(df, is.na(x) | x > 1)
```

```{r}
filter(flights, arr_delay >= 120)
```

```{r}
filter(flights, dest %in% c("IAH", "HOU"))
```

```{r}
filter(flights, carrier %in% c("UA", "AE", "DE"))
```

```{r}
filter(flights, month %in% c(7, 8, 9))
```

```{r}
filter(flights, dep_delay <= 0, arr_delay >= 120)
```

```{r}
filter(flights, dep_delay >= 60, dep_delay - arr_delay >= 30)
```

```{r}
filter(flights, dep_time %in% seq(0, 60*6, 1))
```

```{r}
filter(flights, between(dep_time, 0, 60*6))
```

```{r}
filter(flights, is.na(dep_time))
```

# Arranging with arrange()

```{r}
arrange(flights, year, month, day)
```

```{r}
arrange(flights, desc(arr_delay))
```

```{r}
df <- tibble(x = c(5, 2, NA))
arrange(df, x)
arrange(df, desc(x))
```


```{r}
arrange(df, desc(is.na(x)))
```

```{r}
arrange(flights, desc(dep_delay))
```

```{r}
arrange(flights, dep_delay)
```

```{r}
arrange(flights, air_time)
```

```{r}
arrange(flights, desc(air_time))
```

# Selecting columns with select()

```{r}
select(flights, year, month, day)
```

```{r}
select(flights, year:day)
```

```{r}
select(flights, -(year:day))
```

```{r}
select(flights, contains("delay"))
```

```{r}
rename(flights, y = year, m = month, d = day)
```

```{r}
select(flights, time_hour, air_time, everything())
```

```{r}
select(flights, starts_with("dep"), starts_with("arr"))
```

```{r}
select(flights, dep_time, dep_time)
```

```{r}
vars <- c("year", "month", "day", "dep_delay", "arr_delay")
select(flights, one_of(vars))
```

```{r}
select(flights, contains("time"))
```

# Adding new variables with mutate()

```{r}
flights_sml <- select(flights,
                      year:day,
                      ends_with("delay"),
                      distance,
                      air_time)

mutate(flights_sml, gain = arr_delay - dep_delay,
       speed = distance / air_time * 60)
```

```{r}
mutate(flights_sml, gain = arr_delay - dep_delay,
       hours = air_time / 60,
       gain_per_hour = gain / hours)
```

```{r}
transmute(flights,
          gain = arr_delay - dep_delay,
          hours = air_time / 60,
          gain_per_hour = gain / hours)
```

